# Generated by Django 5.1.4 on 2024-12-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Categoryimage', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(blank=True, max_length=100, null=True)),
                ('Vehiclename', models.CharField(blank=True, max_length=100, null=True)),
                ('Model', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Specification', models.CharField(blank=True, max_length=100, null=True)),
                ('Registration', models.CharField(blank=True, max_length=100, null=True)),
                ('Company', models.CharField(blank=True, max_length=100, null=True)),
                ('Vehicleimage1', models.ImageField(blank=True, null=True, upload_to='vehicle_image')),
                ('Vehicleimage2', models.ImageField(blank=True, null=True, upload_to='vehicle_image')),
                ('Vehicleimage3', models.ImageField(blank=True, null=True, upload_to='vehicle_image')),
            ],
        ),
    ]
