# Generated by Django 5.1.4 on 2024-12-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_subcategorydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='AdditionalData',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
