# Generated by Django 5.1.4 on 2024-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productdb_additionaldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Company',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='Registration',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='Model',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='Specification',
            new_name='Ownername',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='Vehiclename',
            new_name='Productname',
        ),
        migrations.AddField(
            model_name='productdb',
            name='Subcategoryname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
