# Generated by Django 5.1.4 on 2024-12-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalMode',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='auto_approve',
            new_name='auto_approval',
        ),
    ]
