# Generated by Django 5.1.4 on 2024-12-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_delete_approvalmode_delete_yourmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
