# Generated by Django 5.1.4 on 2024-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve', models.BooleanField(default=False)),
            ],
        ),
    ]
