# Generated by Django 5.1.4 on 2024-12-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_approvalmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
