# Generated by Django 5.1.4 on 2024-12-13 21:21
from django.utils.timezone import now

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_approvalmode_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
    ]
