# Generated by Django 5.1.4 on 2024-12-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_productdb_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='created_at',
        ),
    ]
