# Generated by Django 5.1.4 on 2024-12-13 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_productdb_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
