# Generated by Django 5.1.4 on 2024-12-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_productdb_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
