# Generated by Django 5.1.4 on 2025-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_productdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='likes',
            field=models.JSONField(default=list),
        ),
    ]
