# Generated by Django 5.1.4 on 2025-01-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_productdb_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='likes',
        ),
        migrations.AddField(
            model_name='productdb',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='mainapp.productdb')),
            ],
            options={
                'unique_together': {('product', 'liked_by')},
            },
        ),
    ]
