# Generated by Django 5.1.4 on 2025-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_productdb_likes_productdb_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='likes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
