# Generated by Django 5.1.4 on 2025-01-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_productdb_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
