# Generated by Django 5.1.4 on 2025-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_productdb_likes_remove_productdb_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
