# Generated by Django 5.1.4 on 2025-01-22 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_productdb_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='ProfileImage',
        ),
    ]
