# Generated by Django 5.1.4 on 2025-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_dailyrate_adapproved_adpending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adapproved',
            name='user',
        ),
        migrations.RemoveField(
            model_name='adpending',
            name='user',
        ),
        migrations.AddField(
            model_name='adapproved',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adpending',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
