# Generated by Django 5.1.4 on 2025-01-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_remove_adapproved_user_remove_adpending_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapproved',
            name='content',
            field=models.ImageField(null=True, upload_to='ad_content/'),
        ),
        migrations.AddField(
            model_name='adpending',
            name='content',
            field=models.ImageField(null=True, upload_to='ad_content/'),
        ),
    ]
