# Generated by Django 5.1.4 on 2025-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_adapproved_content_adpending_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapproved',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adpending',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
