# Generated by Django 5.1.4 on 2025-01-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
