# Generated by Django 5.1.4 on 2024-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pendingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(blank=True, max_length=100, null=True)),
                ('Subcategoryname', models.CharField(blank=True, max_length=100, null=True)),
                ('Productname', models.CharField(blank=True, max_length=100, null=True)),
                ('Ownername', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Vehicleimage1', models.ImageField(blank=True, null=True, upload_to='vehicle_image')),
                ('Vehicleimage2', models.ImageField(blank=True, null=True, upload_to='vehicle_image')),
                ('Vehicleimage3', models.ImageField(blank=True, null=True, upload_to='vehicle_image')),
                ('AdditionalData', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
