# Generated by Django 5.1.4 on 2024-12-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdb',
            name='AdditionalData',
        ),
    ]
