# Generated by Django 5.1.4 on 2024-12-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_pendingdb_additionaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdb',
            name='AdditionalData',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
