# Generated by Django 5.1.4 on 2024-12-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_signupdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='myitemdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Productname', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pendingdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
