# Generated by Django 5.1.4 on 2024-12-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
