# Generated by Django 5.1.4 on 2025-01-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_productdb_username'),
        ('webapp', '0016_alter_message_content_alter_message_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productdb'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=150),
        ),
    ]
