# Generated by Django 5.1.4 on 2025-01-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_message_product_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myitemdb',
            name='likes',
            field=models.JSONField(default=list),
        ),
    ]
