# Generated by Django 5.1.4 on 2025-01-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_myitemdb_likes_myitemdb_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myitemdb',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
