# Generated by Django 5.1.4 on 2025-01-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='productdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
